# Generated by Django 2.1.4 on 2018-12-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmwypapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='product_name',
            field=models.CharField(default='000', max_length=200),
        ),
    ]
