# Generated by Django 2.1.4 on 2018-12-17 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hmwypapp', '0002_price_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='price',
            name='product_name',
        ),
        migrations.AddField(
            model_name='price',
            name='submitted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='price',
            name='title',
            field=models.CharField(default='product_name', max_length=200),
        ),
    ]
